interface ZIF_C_TV025_CHECKPOINT_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ZC_TV025_CHECKPOINT,
 CREATE_ZC_TV025_CHECKPOINT     TYPE /BOBF/ACT_KEY VALUE '65D968DD9C7E1EDD9EB9DCDA3A96F440',
 DELETE_ZC_TV025_CHECKPOINT     TYPE /BOBF/ACT_KEY VALUE '65D968DD9C7E1EDD9EB9DCDA3A977440',
 LOCK_ZC_TV025_CHECKPOINT       TYPE /BOBF/ACT_KEY VALUE '65D968DD9C7E1EDD9EB9DCDA3A963440',
 SAVE_ZC_TV025_CHECKPOINT       TYPE /BOBF/ACT_KEY VALUE '65D968DD9C7E1EDD9EB9DCDA3A97F440',
 UNLOCK_ZC_TV025_CHECKPOINT     TYPE /BOBF/ACT_KEY VALUE '65D968DD9C7E1EDD9EB9DCDA3A967440',
 UPDATE_ZC_TV025_CHECKPOINT     TYPE /BOBF/ACT_KEY VALUE '65D968DD9C7E1EDD9EB9DCDA3A973440',
 VALIDATE_ZC_TV025_CHECKPOINT   TYPE /BOBF/ACT_KEY VALUE '65D968DD9C7E1EDD9EB9DCDA3A97B440',
      END OF ZC_TV025_CHECKPOINT,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ZC_TV025_CHECKPOINT,
        BEGIN OF LOCK_ZC_TV025_CHECKPOINT,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
        END OF LOCK_ZC_TV025_CHECKPOINT,
        BEGIN OF UNLOCK_ZC_TV025_CHECKPOINT,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
        END OF UNLOCK_ZC_TV025_CHECKPOINT,
      END OF ZC_TV025_CHECKPOINT,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ALTERNATIVE_KEY,
      BEGIN OF ZC_TV025_CHECKPOINT,
 DB_KEY                         TYPE /BOBF/OBM_ALTKEY_KEY VALUE '65D968DD9C7E1EDD9EB9DCDA3A98D440',
      END OF ZC_TV025_CHECKPOINT,
    END OF SC_ALTERNATIVE_KEY .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ZC_TV025_CHECKPOINT,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE '65D968DD9C7E1EDD9EB9DCDA3A961440',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE '65D968DD9C7E1EDD9EB9DCDA3A95D440',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE '65D968DD9C7E1EDD9EB9DCDA3A96D440',
      END OF ZC_TV025_CHECKPOINT,
      BEGIN OF ZC_TV025_CHECKPOINT_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '65D968DD9C7E1EDD9EB9DCDA3A985440',
      END OF ZC_TV025_CHECKPOINT_LOCK,
      BEGIN OF ZC_TV025_CHECKPOINT_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '65D968DD9C7E1EDD9EB9DCDA3A983440',
      END OF ZC_TV025_CHECKPOINT_MESSAGE,
      BEGIN OF ZC_TV025_CHECKPOINT_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '65D968DD9C7E1EDD9EB9DCDA3A987440',
      END OF ZC_TV025_CHECKPOINT_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ZC_TV025_CHECKPOINT,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ZC_TV025_CHECKPOINT,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE '65D968DD9C7E1EDD9EB9DCDA3A953440' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZC_TV025_CHECKPOINT' .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ZC_TV025_CHECKPOINT            TYPE /BOBF/OBM_NODE_KEY VALUE '65D968DD9C7E1EDD9EB9DCDA3A957440',
 ZC_TV025_CHECKPOINT_LOCK       TYPE /BOBF/OBM_NODE_KEY VALUE '65D968DD9C7E1EDD9EB9DCDA3A95F440',
 ZC_TV025_CHECKPOINT_MESSAGE    TYPE /BOBF/OBM_NODE_KEY VALUE '65D968DD9C7E1EDD9EB9DCDA3A95B440',
 ZC_TV025_CHECKPOINT_PROPERTY   TYPE /BOBF/OBM_NODE_KEY VALUE '65D968DD9C7E1EDD9EB9DCDA3A96B440',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ZC_TV025_CHECKPOINT,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  ID                             TYPE STRING VALUE 'ID',
  CODEGRUPPE                     TYPE STRING VALUE 'CODEGRUPPE',
  CODEGRUPPE_TXT                 TYPE STRING VALUE 'CODEGRUPPE_TXT',
  CODE                           TYPE STRING VALUE 'CODE',
  KURZTEXT                       TYPE STRING VALUE 'KURZTEXT',
      END OF ZC_TV025_CHECKPOINT,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ZC_TV025_CHECKPOINT,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE '65D968DD9C7E1EDD9EB9DCDA3A959440',
      END OF ZC_TV025_CHECKPOINT,
    END OF SC_NODE_CATEGORY .
endinterface.
