interface ZIF_I_TV025_VISITOR_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ZI_TV025_VISITOR,
 CREATE_ZI_TV025_VISITOR        TYPE /BOBF/ACT_KEY VALUE '65D968DD9C7E1EDD9EB9E3068058B4A6',
 DELETE_ZI_TV025_VISITOR        TYPE /BOBF/ACT_KEY VALUE '65D968DD9C7E1EDD9EB9E306805934A6',
 LOCK_ZI_TV025_VISITOR          TYPE /BOBF/ACT_KEY VALUE '65D968DD9C7E1EDD9EB9E3068057F4A6',
 SAVE_ZI_TV025_VISITOR          TYPE /BOBF/ACT_KEY VALUE '65D968DD9C7E1EDD9EB9E3068059B4A6',
 UNLOCK_ZI_TV025_VISITOR        TYPE /BOBF/ACT_KEY VALUE '65D968DD9C7E1EDD9EB9E306805834A6',
 UPDATE_ZI_TV025_VISITOR        TYPE /BOBF/ACT_KEY VALUE '65D968DD9C7E1EDD9EB9E3068058F4A6',
 VALIDATE_ZI_TV025_VISITOR      TYPE /BOBF/ACT_KEY VALUE '65D968DD9C7E1EDD9EB9E306805974A6',
      END OF ZI_TV025_VISITOR,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ZI_TV025_VISITOR,
        BEGIN OF LOCK_ZI_TV025_VISITOR,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
        END OF LOCK_ZI_TV025_VISITOR,
        BEGIN OF UNLOCK_ZI_TV025_VISITOR,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
        END OF UNLOCK_ZI_TV025_VISITOR,
      END OF ZI_TV025_VISITOR,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ALTERNATIVE_KEY,
      BEGIN OF ZI_TV025_VISITOR,
 DB_KEY                         TYPE /BOBF/OBM_ALTKEY_KEY VALUE '65D968DD9C7E1EDD9EB9E31AE64794A6',
      END OF ZI_TV025_VISITOR,
    END OF SC_ALTERNATIVE_KEY .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ZI_TV025_VISITOR,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE '65D968DD9C7E1EDD9EB9E3068057D4A6',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE '65D968DD9C7E1EDD9EB9E306805794A6',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE '65D968DD9C7E1EDD9EB9E306805894A6',
      END OF ZI_TV025_VISITOR,
      BEGIN OF ZI_TV025_VISITOR_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '65D968DD9C7E1EDD9EB9E306805A14A6',
      END OF ZI_TV025_VISITOR_LOCK,
      BEGIN OF ZI_TV025_VISITOR_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '65D968DD9C7E1EDD9EB9E3068059F4A6',
      END OF ZI_TV025_VISITOR_MESSAGE,
      BEGIN OF ZI_TV025_VISITOR_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '65D968DD9C7E1EDD9EB9E306805A34A6',
      END OF ZI_TV025_VISITOR_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ZI_TV025_VISITOR,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ZI_TV025_VISITOR,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE '65D968DD9C7E1EDD9EB9E3068056F4A6' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZI_TV025_VISITOR' .
  constants:
    BEGIN OF SC_DETERMINATION,
      BEGIN OF ZI_TV025_VISITOR,
 VISITOR_SAVE                   TYPE /BOBF/DET_KEY VALUE '65D968DD9C7E1EDD9EBA0672126AF69F',
      END OF ZI_TV025_VISITOR,
    END OF SC_DETERMINATION .
  constants:
    BEGIN OF SC_GROUP,
 ZI_TV025_VISITOR               TYPE /BOBF/OBM_GROUP_KEY VALUE '65D968DD9C7E1EDD9EBA0672126B969F',
    END OF SC_GROUP .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ZI_TV025_VISITOR               TYPE /BOBF/OBM_NODE_KEY VALUE '65D968DD9C7E1EDD9EB9E306805734A6',
 ZI_TV025_VISITOR_LOCK          TYPE /BOBF/OBM_NODE_KEY VALUE '65D968DD9C7E1EDD9EB9E3068057B4A6',
 ZI_TV025_VISITOR_MESSAGE       TYPE /BOBF/OBM_NODE_KEY VALUE '65D968DD9C7E1EDD9EB9E306805774A6',
 ZI_TV025_VISITOR_PROPERTY      TYPE /BOBF/OBM_NODE_KEY VALUE '65D968DD9C7E1EDD9EB9E306805874A6',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ZI_TV025_VISITOR,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  PERNR                          TYPE STRING VALUE 'PERNR',
  BIRTH_DATE                     TYPE STRING VALUE 'BIRTH_DATE',
  ENAME                          TYPE STRING VALUE 'ENAME',
  ORGEH_TEXT                     TYPE STRING VALUE 'ORGEH_TEXT',
  CITIZENSHIP                    TYPE STRING VALUE 'CITIZENSHIP',
  PASSP_NUMBER                   TYPE STRING VALUE 'PASSP_NUMBER',
  PASSP_EXPIRY                   TYPE STRING VALUE 'PASSP_EXPIRY',
  BADGE                          TYPE STRING VALUE 'BADGE',
      END OF ZI_TV025_VISITOR,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ZI_TV025_VISITOR,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE '65D968DD9C7E1EDD9EB9E306805754A6',
      END OF ZI_TV025_VISITOR,
    END OF SC_NODE_CATEGORY .
  constants:
    BEGIN OF SC_VALIDATION,
      BEGIN OF ZI_TV025_VISITOR,
 VISITOR_CHECK                  TYPE /BOBF/VAL_KEY VALUE '65D968DD9C7E1EDD9EBA0672126B169F',
      END OF ZI_TV025_VISITOR,
    END OF SC_VALIDATION .
endinterface.
