interface ZIF_C_TV025_APPROVEDBY_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ZC_TV025_APPROVEDBY,
 CREATE_ZC_TV025_APPROVEDBY     TYPE /BOBF/ACT_KEY VALUE 'B7EC402429AA1EEE86F7F3EC001AA923',
 DELETE_ZC_TV025_APPROVEDBY     TYPE /BOBF/ACT_KEY VALUE 'B7EC402429AA1EEE86F7F3EC001B2923',
 LOCK_ZC_TV025_APPROVEDBY       TYPE /BOBF/ACT_KEY VALUE 'B7EC402429AA1EEE86F7F3EC0019E923',
 SAVE_ZC_TV025_APPROVEDBY       TYPE /BOBF/ACT_KEY VALUE 'B7EC402429AA1EEE86F7F3EC001BA923',
 UNLOCK_ZC_TV025_APPROVEDBY     TYPE /BOBF/ACT_KEY VALUE 'B7EC402429AA1EEE86F7F3EC001A2923',
 UPDATE_ZC_TV025_APPROVEDBY     TYPE /BOBF/ACT_KEY VALUE 'B7EC402429AA1EEE86F7F3EC001AE923',
 VALIDATE_ZC_TV025_APPROVEDBY   TYPE /BOBF/ACT_KEY VALUE 'B7EC402429AA1EEE86F7F3EC001B6923',
      END OF ZC_TV025_APPROVEDBY,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ZC_TV025_APPROVEDBY,
        BEGIN OF LOCK_ZC_TV025_APPROVEDBY,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
        END OF LOCK_ZC_TV025_APPROVEDBY,
        BEGIN OF UNLOCK_ZC_TV025_APPROVEDBY,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
        END OF UNLOCK_ZC_TV025_APPROVEDBY,
      END OF ZC_TV025_APPROVEDBY,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ALTERNATIVE_KEY,
      BEGIN OF ZC_TV025_APPROVEDBY,
 DB_KEY                         TYPE /BOBF/OBM_ALTKEY_KEY VALUE 'B7EC402429AA1EEE86F7F3EC001C8923',
      END OF ZC_TV025_APPROVEDBY,
    END OF SC_ALTERNATIVE_KEY .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ZC_TV025_APPROVEDBY,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE 'B7EC402429AA1EEE86F7F3EC0019C923',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE 'B7EC402429AA1EEE86F7F3EC00198923',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE 'B7EC402429AA1EEE86F7F3EC001A8923',
      END OF ZC_TV025_APPROVEDBY,
      BEGIN OF ZC_TV025_APPROVEDBY_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE 'B7EC402429AA1EEE86F7F3EC001C0923',
      END OF ZC_TV025_APPROVEDBY_LOCK,
      BEGIN OF ZC_TV025_APPROVEDBY_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE 'B7EC402429AA1EEE86F7F3EC001BE923',
      END OF ZC_TV025_APPROVEDBY_MESSAGE,
      BEGIN OF ZC_TV025_APPROVEDBY_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE 'B7EC402429AA1EEE86F7F3EC001C2923',
      END OF ZC_TV025_APPROVEDBY_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ZC_TV025_APPROVEDBY,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ZC_TV025_APPROVEDBY,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE 'B7EC402429AA1EEE86F7F3EC0018E923' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZC_TV025_APPROVEDBY' .
  constants:
    BEGIN OF SC_DETERMINATION,
      BEGIN OF ZC_TV025_APPROVEDBY,
 APPROVED_BY_SAVE               TYPE /BOBF/DET_KEY VALUE 'B7EC402429AA1EDE86FAFA6BCC4D5650',
      END OF ZC_TV025_APPROVEDBY,
    END OF SC_DETERMINATION .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ZC_TV025_APPROVEDBY            TYPE /BOBF/OBM_NODE_KEY VALUE 'B7EC402429AA1EEE86F7F3EC00192923',
 ZC_TV025_APPROVEDBY_LOCK       TYPE /BOBF/OBM_NODE_KEY VALUE 'B7EC402429AA1EEE86F7F3EC0019A923',
 ZC_TV025_APPROVEDBY_MESSAGE    TYPE /BOBF/OBM_NODE_KEY VALUE 'B7EC402429AA1EEE86F7F3EC00196923',
 ZC_TV025_APPROVEDBY_PROPERTY   TYPE /BOBF/OBM_NODE_KEY VALUE 'B7EC402429AA1EEE86F7F3EC001A6923',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ZC_TV025_APPROVEDBY,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  APPR_BY                        TYPE STRING VALUE 'APPR_BY',
  APPR_BY_TXT                    TYPE STRING VALUE 'APPR_BY_TXT',
      END OF ZC_TV025_APPROVEDBY,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ZC_TV025_APPROVEDBY,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE 'B7EC402429AA1EEE86F7F3EC00194923',
      END OF ZC_TV025_APPROVEDBY,
    END OF SC_NODE_CATEGORY .
endinterface.
